export const players = [
  {
    id: 1,
    name: "Biko",
    age: 27,
    position: "CM",
    club: "Vipers SC",
    appearances: 110,
    caps: 15,
    countryGoals: 3,
    countryAssists: 5,
    seasonGoals: 15,
    seasonAssists: 20,
    totalGoals: 38,
    totalAssists: 38
  },
  {
    id: 2,
    name: "David",
    age: 19,
    position: "LW",
    club: "SC Villa",
    appearances: 40,
    caps: 4,
    countryGoals: 2,
    countryAssists: 1,
    seasonGoals: 10,
    seasonAssists: 8,
    totalGoals: 21,
    totalAssists: 21
  },
  {
    id: 3,
    name: "Hydra",
    age: 26,
    position: "CB",
    club: "Express FC",
    appearances: 95,
    caps: 8,
    countryGoals: 0,
    countryAssists: 1,
    seasonGoals: 4,
    seasonAssists: 2,
    totalGoals: 7,
    totalAssists: 7
  },
  {
    id: 4,
    name: "JJ",
    age: 21,
    position: "GK",
    club: "BUL FC",
    appearances: 55,
    caps: 3,
    countryGoals: 0,
    countryAssists: 0,
    seasonGoals: 0,
    seasonAssists: 1,
    totalGoals: 1,
    totalAssists: 1
  },
  {
    id: 5,
    name: "Justine",
    age: 22,
    position: "RB",
    club: "Bright Stars",
    appearances: 85,
    caps: 10,
    countryGoals: 0,
    countryAssists: 3,
    seasonGoals: 3,
    seasonAssists: 6,
    totalGoals: 12,
    totalAssists: 12
  },
  {
    id: 6,
    name: "Mickey",
    age: 21,
    position: "ST",
    club: "KCCA",
    appearances: 17,
    caps: 7,
    countryGoals: 2,
    countryAssists: 2,
    seasonGoals: 27,
    seasonAssists: 5,
    totalGoals: 36,
    totalAssists: 36
  },
  {
    id: 7,
    name: "Mulongo",
    age: 24,
    position: "LM",
    club: "Wakiso Giants",
    appearances: 60,
    caps: 12,
    countryGoals: 4,
    countryAssists: 7,
    seasonGoals: 12,
    seasonAssists: 15,
    totalGoals: 38,
    totalAssists: 38
  },
  {
    id: 8,
    name: "Muusazi",
    age: 23,
    position: "CDM",
    club: "URA FC",
    appearances: 50,
    caps: 6,
    countryGoals: 1,
    countryAssists: 3,
    seasonGoals: 2,
    seasonAssists: 9,
    totalGoals: 15,
    totalAssists: 15
  },
  {
    id: 9,
    name: "Muwulo",
    age: 22,
    position: "CB",
    club: "Gaddafi FC",
    appearances: 75,
    caps: 9,
    countryGoals: 0,
    countryAssists: 2,
    seasonGoals: 5,
    seasonAssists: 3,
    totalGoals: 10,
    totalAssists: 10
  },
  {
    id: 10,
    name: "Noah",
    age: 25,
    position: "CM",
    club: "Police FC",
    appearances: 120,
    caps: 14,
    countryGoals: 3,
    countryAssists: 4,
    seasonGoals: 18,
    seasonAssists: 10,
    totalGoals: 35,
    totalAssists: 35
  },
  {
    id: 11,
    name: "Peter",
    age: 22,
    position: "RW",
    club: "Arua Hill",
    appearances: 42,
    caps: 5,
    countryGoals: 1,
    countryAssists: 2,
    seasonGoals: 8,
    seasonAssists: 7,
    totalGoals: 18,
    totalAssists: 18
  }
];
