import type { Metadata } from "next";
import { Inter,Cairo } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { UserProvider } from '@auth0/nextjs-auth0/client';

const inter = Cairo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EIKA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <UserProvider>
     <body className={` min-h-screen ${inter.className}`}>
        <Navbar/>
        {children}
      </body>
     </UserProvider>
    </html>
  );
}
